INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Anglo American', 'AAL');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Associated British Foods', 'ABF');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Admiral Group', 'ADM');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Ashtead Group', 'AHT');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Antofagasta', 'ANTO');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('ARM Holdings', 'ARM');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Aviva', 'AV');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('AstraZeneca', 'AZN');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('BAE Systems', 'BA');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Babcock International Group', 'BAB');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Barclays', 'BARC');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('British American Tobacco', 'BATS');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Barratt Developments', 'BDEV');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Berkeley Group Holdings', 'BKG');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('British Land Co', 'BLND');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('BHP Billiton', 'BLT');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Bunzl', 'BNZL');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('BP', 'BP');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Burberry Group', 'BRBY');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('BT Group', 'BT');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Coca-Cola HBC', 'CCH');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Carnival', 'CCL');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Centrica', 'CNA');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Compass Group', 'CPG');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Capita Group', 'CPI');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('CRH', 'CRH');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Dixons Carphone', 'DC');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('DCC', 'DCC');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Diageo', 'DGE');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Direct Line Insurance Group', 'DLG');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Experian', 'EXPN');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('easyJet', 'EZJ');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Fresnillo', 'FRES');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('GKN', 'GKN');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Glencore', 'GLEN');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('GlaxoSmithKline', 'GSK');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Hargreaves Lansdown', 'HL');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Hammerson', 'HMSO');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('HSBC Holdings', 'HSBA');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('International Consolidated Airlines Group', 'IAG');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('InterContinental Hotels Group', 'IHG');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('3i Group', 'III');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Imperial Brands', 'IMB');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Informa', 'INF');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Intu Properties', 'INTU');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Inmarsat', 'ISAT');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Intertek Group', 'ITRK');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('ITV', 'ITV');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Johnson Matthey', 'JMAT');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Kingfisher', 'KGF');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Land Securities Group', 'LAND');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Legal & General Group', 'LGEN');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Lloyds Banking Group ORD', 'LLOY');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('London Stock Exchange Group', 'LSE');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Mediclinic International', 'MDC');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Merlin Entertainments', 'MERL');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Marks & Spencer Group', 'MKS');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Mondi', 'MNDI');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Morrison (Wm) Supermarkets', 'MRW');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('National Grid', 'NG');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Next', 'NXT');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Old Mutual Group', 'OML');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Provident Financial', 'PFG');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Paddy Power Betfair', 'PPB');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Prudential', 'PRU');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Persimmon', 'PSN');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Pearson', 'PSON');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Reckitt Benckiser Group', 'RB');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Royal Bank of Scotland Group', 'RBS');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Royal Dutch Shell', 'RDSA');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Royal Dutch Shell', 'RDSB');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('RELX', 'REL');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Rexam', 'REX');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Rio Tinto', 'RIO');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Royal Mail', 'RMG');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Rolls-Royce Group', 'RR');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Randgold Resources', 'RRS');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('RSA Insurance Group', 'RSA');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('SABMiller', 'SAB');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Sainsbury', 'SBRY');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Schroders', 'SDR');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Sage Group ', 'SGE');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Shire', 'SHP');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Sky', 'SKY');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Standard Life', 'SL');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Smith & Nephew', 'SN');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('SSE', 'SSE');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Standard Chartered', 'STAN');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('St James\'s Place', 'STJ');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Severn Trent', 'SVT');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Travis Perkins', 'TPK');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Tesco', 'TSCO');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('TUI AG', 'TUI');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Taylor Wimpey', 'TW');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Unilever', 'ULVR');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('United Utilities Group', 'UU');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Vodafone Group', 'VOD');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Wolseley', 'WOS');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Worldpay Group', 'WPG');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('WPP Group', 'WPP');
INSERT INTO `ftse100` (`name`, `symbol`) VALUES ('Whitbread', 'WTB');
