INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('AA', 'AA');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Acacia Mining', 'ACA');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Aberdeen Asset Management', 'ADN');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Aggreko', 'AGK');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Assura Group', 'AGR');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Aldermore Group', 'ALD');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Allied Minds', 'ALM');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Amec Foster Wheeler', 'AMFW');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('AO World', 'AO');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Ashmore Group', 'ASHM');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Aberforth Smaller Companies Trust', 'ASL');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Atkins (W S)', 'ATK');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Alliance Trust', 'ATST');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Auto Trader Group', 'AUTO');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('AVEVA Group', 'AVV');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Barr (A G)', 'BAG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('BBA Aviation', 'BBA');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Tritax Big Box Reit', 'BBOX');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Balfour Beatty', 'BBY');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Beazley', 'BEZ');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Bank of Georgia Holdings', 'BGEO');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('BH Macro Limited GBP', 'BHMG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('B&M European Value Retail', 'BME');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Bankers\' Investment Trust (the)', 'BNKR');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Booker Group', 'BOK');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Bodycote', 'BOY');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Berendsen', 'BRSN');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Brewin Dolphin Holdings', 'BRW');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('British Empire Securities & General Trust', 'BTEM');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('BTG', 'BTG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Britvic', 'BVIC');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Bovis Homes Group', 'BVS');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Brown (N) Group', 'BWNG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Bellway', 'BWY');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Big Yellow Group', 'BYG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Capital & Counties Properties', 'CAPC');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Card Factory', 'CARD');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Close Brothers Group', 'CBG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Computacenter', 'CCC');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Centamin', 'CEY');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Jimmy Choo', 'CHOO');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Cineworld Group', 'CINE');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Circassia Pharmaceuticals', 'CIR');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Clarkson', 'CKN');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Caledonia Investments', 'CLDN');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('CLS Holdings', 'CLI');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Carillion', 'CLLN');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Cairn Energy', 'CNE');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Cobham', 'COB');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Croda International', 'CRDA');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Crest Nicholson Holdings', 'CRST');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('City Of London Investment Trust', 'CTY');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Countrywide', 'CWD');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Cranswick', 'CWK');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Dairy Crest Group', 'DCG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Debenhams', 'DEB');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('DFS Furniture ORD', 'DFS');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Daejan Holdings', 'DJAN');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Derwent London', 'DLN');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Dunelm Group', 'DNLM');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Domino\'s Pizza Group', 'DOM');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Dechra Pharmaceuticals', 'DPH');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Diploma', 'DPLM');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Darty', 'DRTY');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Drax Group', 'DRX');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Dignity', 'DTY');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Electrocomponents', 'ECM');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Edinburgh Investment Trust', 'EDIN');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Elementis', 'ELM');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Electra Private Equity', 'ELTA');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Man Group', 'EMG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Euromoney Institutional Investor', 'ERM');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Essentra', 'ESNT');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('esure Group', 'ESUR');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Entertainment One Group', 'ETO');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Evraz', 'EVR');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('F&C Commercial Property Tst Ld', 'FCPT');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Fidelity China Special Situations', 'FCSS');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Fidessa Group', 'FDSA');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Fidelity European Values', 'FEV');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('FirstGroup', 'FGP');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Finsbury Growth & Income Trust', 'FGT');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Foreign & Colonial Investment Trust', 'FRCL');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('GCP Infrastructure Investments', 'GCP');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Galliford Try', 'GFRD');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('G4S', 'GFS');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Grafton Group', 'GFTU');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Greencore Group', 'GNC');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Greene King', 'GNK');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Genus', 'GNS');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Go-Ahead Group', 'GOG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Great Portland Estates', 'GPOR');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Greggs', 'GRG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Grainger', 'GRI');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Genesis Emerging Markets Fnd Ld', 'GSS');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Hays', 'HAS');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Halfords Group', 'HFD');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Henderson Group', 'HGG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('HICL Infrastructure Co', 'HICL');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Hikma Pharmaceuticals', 'HIK');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Halma', 'HLMA');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Highbridge Multi-strategy Fund Limited Ord Npv Gbp', 'HMSF');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Home Retail Group', 'HOME');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Hastings Group Holdings', 'HSTG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Hansteen Holdings', 'HSTN');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Homeserve', 'HSV');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Hiscox', 'HSX');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Harbourvest Global Private Equity', 'HVPE');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Howden Joinery Group', 'HWDN');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('ICAP', 'IAP');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Ibstock', 'IBST');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Intermediate Capital Group', 'ICP');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('IG Group Holdings', 'IGG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('IMI', 'IMI');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Inchcape', 'INCH');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Indivior', 'INDV');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('International Public Partnership', 'INPP');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Investec', 'INVP');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('International Personal Finance', 'IPF');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('IP Group', 'IPO');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Interserve', 'IRV');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('JPMorgan American IT', 'JAM');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('JD Sports Fashion', 'JD');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Wetherspoon (J D)', 'JDW');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Just Eat', 'JE');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('John Laing Group', 'JLG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('John Laing Infrastructure Fund', 'JLIF');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Jardine Lloyd Thompson Group', 'JLT');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('JPMorgan Emerging Markets Investment Trust', 'JMG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Just Retirement Group', 'JRP');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Jupiter Fund Management', 'JUP');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Kaz Minerals', 'KAZ');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Kier Group', 'KIE');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Keller Group', 'KLR');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Kennedy Wilson Europe Real Estate', 'KWE');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Ladbrokes', 'LAD');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('LondonMetric Property', 'LMP');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Lookers', 'LOOK');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Laird', 'LRD');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Lancashire Holdings', 'LRE');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Mitchells & Butlers', 'MAB');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Marston\'s', 'MARS');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Micro Focus International', 'MCRO');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Mccarthy Stone', 'MCS');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Morgan Advanced Materials', 'MGAM');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Meggitt', 'MGGT');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Millennium & Copthorne Hotels', 'MLC');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Monks Investment Trust', 'MNKS');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Moneysupermarket.com Group', 'MONY');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Michael Page International', 'MPI');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Mercantile Inv Tst', 'MRC');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Melrose', 'MRO');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Marshalls', 'MSLH');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('MITIE Group', 'MTO');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Murray International Trust', 'MYI');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('NB Global Floating Rate Inc Fund', 'NBLS');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('NCC Group', 'NCC');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('National Express Group', 'NEX');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('NMC Health', 'NMC');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Northgate', 'NTG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Ocado Group', 'OCDO');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Ophir Energy', 'OPHR');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Onesavings Bank', 'OSB');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('P2P Global Investments', 'P2P');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Paragon Group of Companies', 'PAG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('PayPoint', 'PAY');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Paysafe Group', 'PAYS');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Polar Capital Technology Trust', 'PCT');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Pendragon', 'PDG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Pets At Home Group', 'PETS');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Petrofac', 'PFC');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Phoenix Group Holdings', 'PHNX');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Perpetual Income And Growth Investment Trust', 'PLI');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Polypipe Group', 'PLP');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Personal Assets Trust', 'PNL');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Pennon Group', 'PNN');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Polymetal International', 'POLY');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Playtech', 'PTEC');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('PZ Cussons', 'PZC');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('QinetiQ Group', 'QQ');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Rathbone Brothers', 'RAT');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('RIT Capital Partners', 'RCP');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Redefine International', 'RDI');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Redrow', 'RDW');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Regus', 'RGU');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Rightmove', 'RMV');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Rank Group', 'RNK');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Rotork', 'ROR');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('RPC Group', 'RPC');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Riverstone Energy Limited', 'RSE');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Renishaw', 'RSW');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Restaurant Group', 'RTN');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Rentokil Initial', 'RTO');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Safestore Holdings', 'SAFE');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Saga', 'SAGA');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Scottish Investment Trust', 'SCIN');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Softcat', 'SCT');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Stagecoach Group', 'SGC');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('SuperGroup', 'SGP');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Segro', 'SGRO');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Shawbrook Group', 'SHAW');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Shaftesbury', 'SHB');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('SIG', 'SHI');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Smith (DS)', 'SMDS');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Smiths Group', 'SMIN');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('St Modwen Properties', 'SMP');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Scottish Mortgage Investment Trust', 'SMT');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('WH Smith', 'SMWH');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Senior', 'SNR');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Sophos Group', 'SOPH');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Sports Direct International', 'SPD');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Spire Healthcare Group', 'SPI');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Spirax-Sarco Engineering', 'SPX');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Serco Group', 'SRP');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('SSP Group', 'SSPG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('SVG Capital', 'SVI');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Savills', 'SVS');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Spectris', 'SXS');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Synthomer', 'SYNT');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('TalkTalk Telecom Group', 'TALK');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Tate & Lyle', 'TATE');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Thomas Cook Group', 'TCG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Ted Baker', 'TED');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Templeton Emerging Markets Investment Trust', 'TEM');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Telecom plus', 'TEP');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Tullett Prebon', 'TLPR');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Tullow Oil', 'TLW');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Temple Bar Investment Trust', 'TMPL');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('The Renewables Infrastructure Group', 'TRIG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('TR Property Investment Trust', 'TRY');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('UBM', 'UBM');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('UDG Healthcare', 'UDG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('UK Commercial Property Trust', 'UKCM');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Ultra Electronics Holdings', 'ULE');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Unite Group', 'UTG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Victrex', 'VCT');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Vectura Group', 'VEC');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Vedanta Resources', 'VED');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Virgin Money Holdings UK', 'VM');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Vesuvius', 'VSVS');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Weir Group', 'WEIR');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('John Wood Group', 'WG');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Wizz Air Holdings', 'WIZZ');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Workspace Group', 'WKP');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('William Hill', 'WMH');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Woodford Patient Capital Trust', 'WPCT');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Witan Investment Trust', 'WTAN');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Worldwide Healthcare Trust', 'WWH');
INSERT INTO `ftse250` (`name`, `symbol`) VALUES ('Zoopla Property Group', 'ZPLA');
